### ISSUE TITLE
Very cool!

### ISSUE THREAD

**Issue by RobLoach** [scastd/raygui-cpp#1]
Nice work putting this together. Glad to see more helpful integrations with raylib pop up.

Is it possible to have some children to each component?

``` cpp
// Initialize the GUI
WindowBox window("Hello");
Button button("Launch");
window.add(button);

// Render
window.Show()
```

.... And have it display the button in the window?

**Comment by scastd** [comment]
It is not currently implemented, but it is a great idea for the future.
Maybe the `Style` class can be used to define the position inside the parent component.

Thanks for your feedback!
